### ISSUE TITLE
Spec text?

### ISSUE THREAD

**Issue by binji** [WebAssembly/nontrapping-float-to-int-conversions#1]
@sunfishcode 

I've been working on spec text for threads + bulk memory operations already, so I'd be happy to pick up the spec text for this too, if you like.

**Comment by sunfishcode** [comment]
That would be helpful, thanks.

**Comment by binji** [comment]
See https://github.com/binji/nontrapping-float-to-int-conversions/commit/5b893585ecb12d5a516612b9b23ba5b51a789587.

And the rendered version here: https://binji.github.io/nontrapping-float-to-int-conversions/

I merged from spec's master branch first because there have been some recent fixes, but wasn't able to push that here (I don't have permission), so I can't really do a PR.

**Comment by binji** [comment]
Interpreter implementation: https://github.com/binji/nontrapping-float-to-int-conversions/commit/002d9ef1f4c8cb8582e33b2b9817a3d1e5a449bd

The actual conversions are kinda nasty, could be cleaned up. But the tests pass :-)

**Comment by sunfishcode** [comment]
I've now rebased this repo on the spec trunk.

**Comment by binji** [comment]
Thanks, I was able to create the PRs.

**Comment by sunfishcode** [comment]
Thanks, I've now merged them.
