### ISSUE TITLE
Prefix byte name not applicable

### ISSUE THREAD

**Issue by tlively** [WebAssembly/nontrapping-float-to-int-conversions#5]
This proposal says that opcode prefix byte `0xfc` is for numeric operations, but this prefix is also used in the bulk memory proposal for decidedly non-numeric operations. The meaning of this prefix bytes should either be clarified in this proposal or the bulk memory proposal should use a new prefix byte.

**Comment by sunfishcode** [comment]
Yes, in https://github.com/WebAssembly/meetings/blob/master/2018/CG-04-03.md#process-for-assigning-opcode-numbers, the committee decided to rename "numeric" to "misc".

(Historical note, this overturned https://github.com/WebAssembly/meetings/blob/master/2017/CG-05.md, where some people objected to a "miscellaneous" namespace and preferred "numeric").
